anomaly_clean: false
batch_size: 16
conf_cache_level: 1
data_type: molecule
epochs: 10
freeze_layers: null
freeze_layers_reversed: false
kfold: 5
learning_rate: 0.0001
load_model_dir: null
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics: auc
model_name: unimolv1
model_size: 84m
num_classes: 1
patience: 5
pretrained_dict_path: null
pretrained_model_path: null
remove_hs: false
seed: 42
smi_strict: true
smiles_col: smiles
split: random
split_group_col: scaffold
split_method: 5fold_random
split_seed: 42
target_col_prefix: TARGET
target_cols: label
target_normalize: auto
task: classification
use_amp: true
use_cuda: true
use_ddp: false
use_gpu: all
warmup_ratio: 0.03
